### ISSUE TITLE
lintian: bad-whatis-entry

### ISSUE THREAD

**Issue by galaxysite** [stseelig/libttaR#4]
Hi,

I try make .deb package and get lintian warnings:

`W: gorg64: bad-whatis-entry [usr/share/man/man3/libttar_misc.3.gz]`
`W: gorg64: groff-message troff:<standard input>:9: warning: macro '.......' not defined [usr/share/man/man1/ttar.1.gz:1]`
`W: gorg64: groff-message troff:<standard input>:9: warning: macro '.......' not defined [usr/share/man/man3/libttar_crc32.3.gz:1]`
`W: gorg64: groff-message troff:<standard input>:9: warning: macro '.......' not defined [usr/share/man/man3/libttar_misc.3.gz:1]`
`W: gorg64: groff-message troff:<standard input>:9: warning: macro '.......' not defined [usr/share/man/man3/libttar_pcm_read.3.gz:1]`
`W: gorg64: groff-message troff:<standard input>:9: warning: macro '.......' not defined [usr/share/man/man3/libttar_tta_encode.3.gz:1]`

**Comment by stseelig** [comment]
thank you

i could not figure out how to use lintian on individual source files but i think that i fixed it

bad-what-is-entry caused by no '-' in the name
bad macro caused by the long comment lines
