### ISSUE TITLE
lintian. Part 2. Dots.

### ISSUE THREAD

**Issue by galaxysite** [stseelig/libttaR#5]
Hi,

Thanx for change the manuals: warning about what-is-entry leave.

But stay up warning about dots.

Messages about dots touch only top 9 lines of files.
If I delete it, warning is leave.

E.g. if delete:

'# t
.# Title: libttaR_pcm_read
.# Author: Shane Seelig
.# Date: 2024-11-18
.# Source: libttaR 1.2
.# Language: English
.#
.# ##########################################################################

**Comment by stseelig** [comment]
i changed the comments to '.\\"' to match man 7 man

**Comment by galaxysite** [comment]
Excellent. All Ok. Thank You !

**Comment by galaxysite** [comment]
Close.
